[package]
name = "google-fonts"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
reqwest = { version = "0.12.5", features = ["http2", "rustls-tls", "blocking"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
strum = { version = "0.26.3", features = ["derive", "strum_macros"] }

[build-dependencies]
anyhow = "1.0.86"
gen = { path = "../gen" }

[dev-dependencies]
ttf-parser = "0.24.0"
