[package]
name = "gen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
cargo_toml = "0.20.3"
dirs = "5.0.1"
heck = "0.5.0"
itertools = "0.13.0"
reqwest = { version = "0.12.5", features = [
    "http2",
    "rustls-tls",
    "blocking",
] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
skia-safe = { version = "0.75.0", features = ["textlayout"] }
strum = { version = "0.26.3", features = ["derive", "strum_macros"] }
toml = "0.8.15"

[dev-dependencies]
ttf-parser = "0.24.0"
